[package]
edition = "2018"
name = "threepy"
version = "0.1.0"
authors = ["Sergiusz Bazanski <q3k@q3k.org>"]

[dependencies]
env_logger = "0.6.1"
log = "0.4.6"
vulkano = "0.11.1"
vulkano-win = "0.11.1"
winit = "0.18.0"
