load("//tools/bzl:glsl.bzl", "glsl_binary")

glsl_binary(
    name = "triangle_vert",
    srcs = [
        "triangle.vert"
    ],
    visibility = ["//engine:__pkg__"],
)

glsl_binary(
    name = "triangle_frag",
    srcs = [
        "triangle.frag"
    ],
    visibility = ["//engine:__pkg__"],
)
